// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgv4y8Ip-J5ztCYuYosOd3gGKR5iM3LSc',
    appId: '1:544145026249:web:ec66693ad668cbc0013118',
    messagingSenderId: '544145026249',
    projectId: 'campus-connect-49800',
    authDomain: 'campus-connect-49800.firebaseapp.com',
    storageBucket: 'campus-connect-49800.firebasestorage.app',
    measurementId: 'G-GR98LJBB5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZMmPlazgqJQiaHF9jmry_aOXRXOnwkZk',
    appId: '1:544145026249:android:76104e51012736d6013118',
    messagingSenderId: '544145026249',
    projectId: 'campus-connect-49800',
    storageBucket: 'campus-connect-49800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMoYGNf5C1sZKceKUk8b456mpERAC4e1c',
    appId: '1:544145026249:ios:65936640a5c92287013118',
    messagingSenderId: '544145026249',
    projectId: 'campus-connect-49800',
    storageBucket: 'campus-connect-49800.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMoYGNf5C1sZKceKUk8b456mpERAC4e1c',
    appId: '1:544145026249:ios:65936640a5c92287013118',
    messagingSenderId: '544145026249',
    projectId: 'campus-connect-49800',
    storageBucket: 'campus-connect-49800.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgv4y8Ip-J5ztCYuYosOd3gGKR5iM3LSc',
    appId: '1:544145026249:web:339e97d33d5ba2bb013118',
    messagingSenderId: '544145026249',
    projectId: 'campus-connect-49800',
    authDomain: 'campus-connect-49800.firebaseapp.com',
    storageBucket: 'campus-connect-49800.firebasestorage.app',
    measurementId: 'G-S2GLLLMG00',
  );

}