// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeszJXpLocIRiXEo7pt84sPdeOJdf6AhA',
    appId: '1:585800657676:web:263059cad7c5434c6a3729',
    messagingSenderId: '585800657676',
    projectId: 'inventory-ms-904bc',
    authDomain: 'inventory-ms-904bc.firebaseapp.com',
    storageBucket: 'inventory-ms-904bc.firebasestorage.app',
    measurementId: 'G-P6WWE742JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxX131rMwgkIbYdMlWsy4-7ahRGsFwwk8',
    appId: '1:585800657676:android:692d95bad31f3fd66a3729',
    messagingSenderId: '585800657676',
    projectId: 'inventory-ms-904bc',
    storageBucket: 'inventory-ms-904bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrZFfstWRwL6UkPqzp1xMKGsQy7fOoPJ0',
    appId: '1:585800657676:ios:34f36764add551c66a3729',
    messagingSenderId: '585800657676',
    projectId: 'inventory-ms-904bc',
    storageBucket: 'inventory-ms-904bc.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrZFfstWRwL6UkPqzp1xMKGsQy7fOoPJ0',
    appId: '1:585800657676:ios:34f36764add551c66a3729',
    messagingSenderId: '585800657676',
    projectId: 'inventory-ms-904bc',
    storageBucket: 'inventory-ms-904bc.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeszJXpLocIRiXEo7pt84sPdeOJdf6AhA',
    appId: '1:585800657676:web:dfe6a49398c548a56a3729',
    messagingSenderId: '585800657676',
    projectId: 'inventory-ms-904bc',
    authDomain: 'inventory-ms-904bc.firebaseapp.com',
    storageBucket: 'inventory-ms-904bc.firebasestorage.app',
    measurementId: 'G-CSFNFHJC6W',
  );
}
