// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSaWb_4GmDZSCnENpEVdD6UfcEvMeWAXs',
    appId: '1:274567871305:web:41706abfa73ff870193898',
    messagingSenderId: '274567871305',
    projectId: 'week5project-62d4d',
    authDomain: 'week5project-62d4d.firebaseapp.com',
    storageBucket: 'week5project-62d4d.firebasestorage.app',
    measurementId: 'G-1WJ6MN1VTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeFmV3_cy35YyXSrGltLw8zmJUlI1i2_4',
    appId: '1:274567871305:android:c9977c9949dd64ff193898',
    messagingSenderId: '274567871305',
    projectId: 'week5project-62d4d',
    storageBucket: 'week5project-62d4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATvU0Jwph16u8m5ww3fpplrwYu5QO8AdA',
    appId: '1:274567871305:ios:6b02d20a31986b23193898',
    messagingSenderId: '274567871305',
    projectId: 'week5project-62d4d',
    storageBucket: 'week5project-62d4d.firebasestorage.app',
    iosBundleId: 'com.example.week5Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATvU0Jwph16u8m5ww3fpplrwYu5QO8AdA',
    appId: '1:274567871305:ios:6b02d20a31986b23193898',
    messagingSenderId: '274567871305',
    projectId: 'week5project-62d4d',
    storageBucket: 'week5project-62d4d.firebasestorage.app',
    iosBundleId: 'com.example.week5Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSaWb_4GmDZSCnENpEVdD6UfcEvMeWAXs',
    appId: '1:274567871305:web:d10fe3b3d634b1c6193898',
    messagingSenderId: '274567871305',
    projectId: 'week5project-62d4d',
    authDomain: 'week5project-62d4d.firebaseapp.com',
    storageBucket: 'week5project-62d4d.firebasestorage.app',
    measurementId: 'G-SHTQRX40WW',
  );
}
